#pragma once

#ifdef __cplusplus
#include <utils/pch.hpp>
/// Host
using float4 = tinyd3d::vec4;
using uint = uint32_t;
#else
/// HLSL
#endif


// Used in inline root constants
struct DrawConstants {
	int moo;
	float bar;
};

struct LightConstants {
	float4 color;
};

// Test particle structure
struct GPUParticle {
	// actual data is randomly generated by the gpu
    float4 pos; 
	uint state;
};

